
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author Marcos
 */
public class ContrasenaGestor extends javax.swing.JFrame {

    int intentos = 3;
    Empleado emp;
    RegistroEmpleado regEmp;
    
    public ContrasenaGestor(Empleado e) {
        initComponents();
        this.setVisible(true);
        this.emp = e;
        this.setTitle("Contraseña");
        txtEmpleContra.setText(String.valueOf(e.getCodEmpleado()));
        botonEntrarGestor.setText("ENTRAR");
        txtConfirmacionContra.setVisible(false);
        inputConfirmacionContra.setVisible(false);
    }
    
    public ContrasenaGestor(RegistroEmpleado rE){
        initComponents();
        this.setVisible(true);
        this.regEmp = rE;
        
        this.setTitle("Nuevo gestor");
        txtContrasena.setText("Contraseña de nuevo gestor");
        botonEntrarGestor.setText("REGISTRAR");
        txtConfirmacionContra.setVisible(true);
        inputConfirmacionContra.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoContra = new javax.swing.JPanel();
        botonEntrarGestor = new javax.swing.JButton();
        txtEmpleContra = new javax.swing.JLabel();
        inputContrasena = new javax.swing.JPasswordField();
        txtContrasena = new javax.swing.JLabel();
        inputConfirmacionContra = new javax.swing.JPasswordField();
        txtConfirmacionContra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondoContra.setBackground(new java.awt.Color(204, 204, 204));

        botonEntrarGestor.setText("ENTRAR");
        botonEntrarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarGestorActionPerformed(evt);
            }
        });

        txtEmpleContra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmpleContra.setText("EMPLEADO: COD_EMP");

        inputContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputContrasenaActionPerformed(evt);
            }
        });

        txtContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContrasena.setText("Introduzca su contraseña:");

        inputConfirmacionContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConfirmacionContraActionPerformed(evt);
            }
        });

        txtConfirmacionContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConfirmacionContra.setText("Confirme la contraseña:");

        javax.swing.GroupLayout panelFondoContraLayout = new javax.swing.GroupLayout(panelFondoContra);
        panelFondoContra.setLayout(panelFondoContraLayout);
        panelFondoContraLayout.setHorizontalGroup(
            panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoContraLayout.createSequentialGroup()
                .addGroup(panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoContraLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(botonEntrarGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoContraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEmpleContra))
                    .addGroup(panelFondoContraLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContrasena)
                            .addComponent(txtConfirmacionContra))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputConfirmacionContra, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelFondoContraLayout.setVerticalGroup(
            panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoContraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmpleContra)
                .addGap(38, 38, 38)
                .addGroup(panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelFondoContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputConfirmacionContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmacionContra))
                .addGap(28, 28, 28)
                .addComponent(botonEntrarGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputContrasenaActionPerformed

    private void botonEntrarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarGestorActionPerformed
        try{
            // Si se ha accedido a la interfaz desde el fichaje
            if (this.emp != null) {
                if (!GestorBD.compruebaContrasena(inputContrasena.getText(), String.valueOf(emp.getCodEmpleado()))) {
                    intentos--;
                    inputContrasena.setText("");
                    if (this.intentos == 0) {
                        JOptionPane.showMessageDialog(this, "Has superado el límite de intentos\nFichaje cancelado");
                        Fichaje f = new Fichaje();
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Contraseña errónea.\nIntentos restantes: " + intentos);
                    }
                } 
                else {
                    JOptionPane.showMessageDialog(this, "Contraseña correcta.\n"
                            + "Entrando en el gestor: " + this.emp.getCodEmpleado() + ", " + this.emp.getNombre());
                    VistaGestor gestor = new VistaGestor(this.emp, GestorBD.horaActual());
                    this.setVisible(false);
                }
            }
            
            // Si se ha accedido desde Registro de empleados
            else{
                confirmarContraNuevoGestor();
                
            }
            
        }
        catch (MyException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonEntrarGestorActionPerformed

    private void inputConfirmacionContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConfirmacionContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConfirmacionContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntrarGestor;
    private javax.swing.JPasswordField inputConfirmacionContra;
    private javax.swing.JPasswordField inputContrasena;
    private javax.swing.JPanel panelFondoContra;
    private javax.swing.JLabel txtConfirmacionContra;
    private javax.swing.JLabel txtContrasena;
    private javax.swing.JLabel txtEmpleContra;
    // End of variables declaration//GEN-END:variables

    private int comprueba() throws MyException {
        if (intentos == 0) {
            return intentos;
        } 
        else if (!GestorBD.compruebaContrasena(inputContrasena.getText(), String.valueOf(emp.getCodEmpleado()))) {
            intentos--;
            return intentos;
        } 
        else if (GestorBD.compruebaContrasena(inputContrasena.getText(), String.valueOf(emp.getCodEmpleado()))) {
            JOptionPane.showMessageDialog(this, "Contraseña correcta.\nEntrando en usuario "
                    + emp.getCodEmpleado() + ", " + emp.getNombre());
            return -1;
        }
        return 0;
    }
    
    private void confirmarContraNuevoGestor() throws MyException{
        if(inputContrasena.getText().equals("")){
            throw new MyException("El campo contraseña no puede estar vacío.");
        }
        else if(inputConfirmacionContra.getText().equals("")){
            throw new MyException("Hay que confirmar la contraseña");
        }
        else if(inputContrasena.getText().equals(inputConfirmacionContra.getText())){
            throw new MyException("Las contraseñas no coinciden");
        }
    }
}
