/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import gestor.GestorBD;
import modelo.Empleado;
import modelo.Lote;
import modelo.Maquina;

/**
 *
 * @author Marcos
 */
public class Encargado extends javax.swing.JFrame {

    Empleado empleado;
    Lote lote;
    Maquina maquina;
    int emple2;
    int emple3;
    String horaInicial;
    String codError;
    
    public Encargado(Empleado emp, Lote lote, Maquina maq, int emp2, int emp3, String horaIni) {
        initComponents();
        this.setVisible(true);
        
        this.empleado = emp;
        this.lote = lote;
        this.maquina = maq;
        this.emple2 = emp2;
        this.emple3 = emp3;
        this.horaInicial = horaIni;
        
        textoEncarEmple.setText("EMPLEADO: " + empleado.getCodEmpleado());
        texoEncarLote.setText("LOTE: " + lote.getCodLote());
        textoEncarMaquina.setText("MAQUINA: " + maquina.getCodMaquina());
        encarFecha.setText(GestorBD.fecha());
        this.setTitle(String.valueOf(empleado.getCodEmpleado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonEncarSalir = new javax.swing.JButton();
        botonEncarListaError = new javax.swing.JButton();
        textoEncarMaquina = new javax.swing.JLabel();
        texoEncarLote = new javax.swing.JLabel();
        textoEncarEmple = new javax.swing.JLabel();
        panelEncarSuperior = new javax.swing.JPanel();
        encarFecha = new javax.swing.JLabel();
        nomEncarEmpresa = new javax.swing.JLabel();
        botonEncarRegError = new javax.swing.JButton();
        botonEncarNuevoLote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEncarSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonEncarSalir.setText("TERMINAR FICHAJE");
        botonEncarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncarSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonEncarSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, 57));

        botonEncarListaError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonEncarListaError.setText("LISTA DE ERRORES");
        botonEncarListaError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncarListaErrorActionPerformed(evt);
            }
        });
        jPanel1.add(botonEncarListaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 150, 57));

        textoEncarMaquina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoEncarMaquina.setText("MAQUINA: COD_MAQUINA");
        jPanel1.add(textoEncarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 40));

        texoEncarLote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        texoEncarLote.setText("LOTE: COD_LOTE");
        jPanel1.add(texoEncarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 170, 40));

        textoEncarEmple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoEncarEmple.setText("EMPLEADO: COD_EMP");
        jPanel1.add(textoEncarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 40));

        panelEncarSuperior.setBackground(new java.awt.Color(0, 102, 204));

        encarFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        encarFecha.setForeground(new java.awt.Color(240, 240, 240));
        encarFecha.setText("Fecha");

        nomEncarEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nomEncarEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        nomEncarEmpresa.setText("CoX Manager");

        javax.swing.GroupLayout panelEncarSuperiorLayout = new javax.swing.GroupLayout(panelEncarSuperior);
        panelEncarSuperior.setLayout(panelEncarSuperiorLayout);
        panelEncarSuperiorLayout.setHorizontalGroup(
            panelEncarSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncarSuperiorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nomEncarEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(encarFecha)
                .addGap(87, 87, 87))
        );
        panelEncarSuperiorLayout.setVerticalGroup(
            panelEncarSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncarSuperiorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelEncarSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomEncarEmpresa)
                    .addComponent(encarFecha))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(panelEncarSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        botonEncarRegError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonEncarRegError.setText("REGISTRAR ERROR");
        botonEncarRegError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncarRegErrorActionPerformed(evt);
            }
        });
        jPanel1.add(botonEncarRegError, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 150, 57));

        botonEncarNuevoLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonEncarNuevoLote.setText("NUEVO LOTE");
        botonEncarNuevoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncarNuevoLoteActionPerformed(evt);
            }
        });
        jPanel1.add(botonEncarNuevoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 150, 57));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEncarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncarSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEncarSalirActionPerformed

    private void botonEncarListaErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncarListaErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEncarListaErrorActionPerformed

    private void botonEncarRegErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncarRegErrorActionPerformed
        RegistroErrores re = new RegistroErrores(this);
        this.setVisible(false);
    }//GEN-LAST:event_botonEncarRegErrorActionPerformed

    private void botonEncarNuevoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncarNuevoLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEncarNuevoLoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEncarListaError;
    private javax.swing.JButton botonEncarNuevoLote;
    private javax.swing.JButton botonEncarRegError;
    private javax.swing.JButton botonEncarSalir;
    private javax.swing.JLabel encarFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomEncarEmpresa;
    private javax.swing.JPanel panelEncarSuperior;
    private javax.swing.JLabel texoEncarLote;
    private javax.swing.JLabel textoEncarEmple;
    private javax.swing.JLabel textoEncarMaquina;
    // End of variables declaration//GEN-END:variables

    public String getCodEmpEncar(){
        return String.valueOf(this.empleado.getCodEmpleado());
    }
    
    public String getCodLoteEncar(){
        return String.valueOf(this.lote.getCodLote());
    }

    public String getCodMaqEncar(){
        return String.valueOf(this.maquina.getCodMaquina());
    }
    
    public String getNomMaqEncar(){
        return String.valueOf(this.maquina.getNombreMaquina());
    }
    
    public void volver(){
        this.setVisible(true);
    }
}
