/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Lote;

/**
 *
 * @author Marcos
 */
public class EstadoLote extends javax.swing.JFrame {

    VistaEncargado encargado;
    
    public EstadoLote(VistaEncargado vE) {
        initComponents();
        this.encargado = vE;
        this.setTitle("Estado de lote");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoEstadoLotes = new javax.swing.JPanel();
        panelInforSuperior1 = new javax.swing.JPanel();
        txtInforFecha = new javax.swing.JLabel();
        txtInforEmpresa = new javax.swing.JLabel();
        textoCodLoteEstado = new javax.swing.JLabel();
        inputCodLoteEstado = new javax.swing.JTextField();
        botonEstadoLote = new javax.swing.JButton();
        cantProducidaLoteEstado = new javax.swing.JLabel();
        ultimaMaquinaLoteEstado = new javax.swing.JLabel();
        errorLoteEstado = new javax.swing.JLabel();
        botonSalirEstadoLotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelFondoEstadoLotes.setPreferredSize(new java.awt.Dimension(650, 400));
        panelFondoEstadoLotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInforSuperior1.setBackground(new java.awt.Color(0, 102, 204));
        panelInforSuperior1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInforFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtInforFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtInforFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtInforFecha.setText("Fecha");
        panelInforSuperior1.add(txtInforFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        txtInforEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtInforEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtInforEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        txtInforEmpresa.setText("CoX Manager");
        panelInforSuperior1.add(txtInforEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelFondoEstadoLotes.add(panelInforSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        textoCodLoteEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoCodLoteEstado.setText("CODIGO DE LOTE:");
        panelFondoEstadoLotes.add(textoCodLoteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        panelFondoEstadoLotes.add(inputCodLoteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 210, -1));

        botonEstadoLote.setText("CONSULTAR");
        botonEstadoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstadoLoteActionPerformed(evt);
            }
        });
        panelFondoEstadoLotes.add(botonEstadoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 150, 50));

        cantProducidaLoteEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantProducidaLoteEstado.setText("CANTIDAD PRODUCIDA:");
        panelFondoEstadoLotes.add(cantProducidaLoteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        ultimaMaquinaLoteEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ultimaMaquinaLoteEstado.setText("ÚLTIMA MÁQUINA: ");
        panelFondoEstadoLotes.add(ultimaMaquinaLoteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        errorLoteEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorLoteEstado.setText("ERROR EN PRODUCCIÓN: ");
        panelFondoEstadoLotes.add(errorLoteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        botonSalirEstadoLotes.setText("SALIR");
        botonSalirEstadoLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirEstadoLotesActionPerformed(evt);
            }
        });
        panelFondoEstadoLotes.add(botonSalirEstadoLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoEstadoLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoEstadoLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEstadoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstadoLoteActionPerformed
        ultimaMaquinaLoteEstado.setText("ÚLTIMA MÁQUINA: ");
        errorLoteEstado.setText("ERRORES EN PRODUCCIÓN: ");
        cantProducidaLoteEstado.setText("CANTIDAD PRODUCIDA: ");
        
        try {
            Lote l = GestorBD.existeLote(inputCodLoteEstado.getText());
            
            if(l != null){
                Integer[] datosLote = new Integer[2];
                datosLote = GestorBD.consultaEstadoLote(l.getCodLote());
                ultimaMaquinaLoteEstado.setText(ultimaMaquinaLoteEstado.getText() + datosLote[0]);
                
                cantProducidaLoteEstado.setText(cantProducidaLoteEstado.getText() + datosLote[1]);
                HashSet<String> errores = new HashSet<>();
                GestorBD.consultaErroresLote(l.getCodLote(), errores);
                //borraDuplicados(errores);
                String codigosErrores = "";
                for (String codErr : errores) {
                    codigosErrores += codErr +", ";
                }
                errorLoteEstado.setText(errorLoteEstado.getText() + codigosErrores);
            }
            else{
                JOptionPane.showMessageDialog(this, "El lote introducido no existe.");
            }
            
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonEstadoLoteActionPerformed

    private void botonSalirEstadoLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirEstadoLotesActionPerformed
        encargado.volver();
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirEstadoLotesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        encargado.volver();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        encargado.volver();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstadoLote;
    private javax.swing.JButton botonSalirEstadoLotes;
    private javax.swing.JLabel cantProducidaLoteEstado;
    private javax.swing.JLabel errorLoteEstado;
    private javax.swing.JTextField inputCodLoteEstado;
    private javax.swing.JPanel panelFondoEstadoLotes;
    private javax.swing.JPanel panelInforSuperior1;
    private javax.swing.JLabel textoCodLoteEstado;
    private javax.swing.JLabel txtInforEmpresa;
    private javax.swing.JLabel txtInforFecha;
    private javax.swing.JLabel ultimaMaquinaLoteEstado;
    // End of variables declaration//GEN-END:variables

    /*private static void borraDuplicados(ArrayList<String> e){
        String codErrAux = "";
        ArrayList<String> erroresBorrar = new ArrayList<>();
        for (String error : e) {
            if(!error.equals(codErrAux)){
                codErrAux = error;
            }
            else{
                erroresBorrar.add(error);
            }
        }
        for (String error : erroresBorrar) {
            e.remove(error);
        }
    }*/


}
