/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import jasper.GeneraInforme;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Informes extends javax.swing.JFrame {

    VistaGestor gestor;
    
    public Informes(VistaGestor vG) {
        initComponents();
        this.gestor = vG;
        
        this.setVisible(true);
        this.setTitle("Generar Informe");
        inputFechaInicialInforme.setVisible(false);
        inputFechaFinalInforme.setVisible(false);
        txtFechaFin.setVisible(false);
        txtFechaInicio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelInforSuperior1 = new javax.swing.JPanel();
        txtInforFecha = new javax.swing.JLabel();
        txtInforEmpresa = new javax.swing.JLabel();
        listaOpcionesInforme = new javax.swing.JComboBox<>();
        txtInforme = new javax.swing.JLabel();
        inputFechaFinalInforme = new com.toedter.calendar.JDateChooser();
        botonGenerarInforme = new javax.swing.JButton();
        inputFechaInicialInforme = new com.toedter.calendar.JDateChooser();
        txtFechaFin = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JLabel();
        txtInformeCodEmp = new javax.swing.JLabel();
        inputInformeCodEmp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 386));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        panelInforSuperior1.setBackground(new java.awt.Color(0, 102, 204));
        panelInforSuperior1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInforFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtInforFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtInforFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtInforFecha.setText("Fecha");
        panelInforSuperior1.add(txtInforFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        txtInforEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtInforEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtInforEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        txtInforEmpresa.setText("CoX Manager");
        panelInforSuperior1.add(txtInforEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        listaOpcionesInforme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPLEADO", "LOTES", "ERRORES" }));
        listaOpcionesInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaOpcionesInformeActionPerformed(evt);
            }
        });

        txtInforme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInforme.setText("Seleccione el objeto del informe:");

        inputFechaFinalInforme.setDateFormatString("dd-MM-yyyy");

        botonGenerarInforme.setText("GENERAR INFORME");
        botonGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarInformeActionPerformed(evt);
            }
        });

        inputFechaInicialInforme.setDateFormatString("dd-MM-yyyy");

        txtFechaFin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaFin.setText("Seleccione el dia final del informe:");

        txtFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaInicio.setText("Seleccione el dia inicial del informe:");

        txtInformeCodEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInformeCodEmp.setText("Introduzca el codigo de empleado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInforSuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(botonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtInforme)
                                .addGap(18, 18, 18)
                                .addComponent(listaOpcionesInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFechaInicio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputFechaInicialInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txtFechaFin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputFechaFinalInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtInformeCodEmp))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(inputInformeCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelInforSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaOpcionesInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInforme))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputFechaInicialInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputFechaFinalInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaFin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(botonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInformeCodEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputInformeCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaOpcionesInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaOpcionesInformeActionPerformed
        
        switch (listaOpcionesInforme.getSelectedItem().toString()) {
            case "EMPLEADO":
                txtInformeCodEmp.setVisible(true);
                inputInformeCodEmp.setVisible(true);
                
                inputFechaInicialInforme.setVisible(false);
                inputFechaInicialInforme.setDate(null);
                inputFechaFinalInforme.setVisible(false);
                inputFechaFinalInforme.setDate(null);
                txtFechaFin.setVisible(false);
                txtFechaInicio.setVisible(false);
                break;
            case "ERRORES":
                inputFechaInicialInforme.setVisible(true);
                inputFechaFinalInforme.setVisible(true);
                txtFechaFin.setVisible(true);
                txtFechaInicio.setVisible(true);
                
                txtInformeCodEmp.setVisible(false);
                inputInformeCodEmp.setVisible(false);
                inputInformeCodEmp.setText(null);
                break;
            default:
                txtInformeCodEmp.setVisible(false);
                inputInformeCodEmp.setVisible(false);
                inputFechaInicialInforme.setVisible(false);
                inputFechaFinalInforme.setVisible(false);
                inputFechaInicialInforme.setDate(null);
                inputFechaFinalInforme.setDate(null);
                
                txtFechaFin.setVisible(false);
                txtFechaInicio.setVisible(false);
                inputInformeCodEmp.setText(null);
                break;
        }
    }//GEN-LAST:event_listaOpcionesInformeActionPerformed

    private void botonGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarInformeActionPerformed
        if(listaOpcionesInforme.getSelectedIndex() == 0 || listaOpcionesInforme.getSelectedIndex() == 2){
            JOptionPane.showMessageDialog(this, "Este informe aún no está implementado.");
        }
        else{
            String nombreInformeGenerado = "";
            GeneraInforme informe = new GeneraInforme(GestorBD.getConexion());
            try {
                nombreInformeGenerado = informe.generarInforme();
            } catch (MyException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            JOptionPane.showMessageDialog(this, "Informe generado: " + nombreInformeGenerado);
            this.setVisible(false);
            gestor.volver();
        }
    }//GEN-LAST:event_botonGenerarInformeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarInforme;
    private com.toedter.calendar.JDateChooser inputFechaFinalInforme;
    private com.toedter.calendar.JDateChooser inputFechaInicialInforme;
    private javax.swing.JTextField inputInformeCodEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listaOpcionesInforme;
    private javax.swing.JPanel panelInforSuperior1;
    private javax.swing.JLabel txtFechaFin;
    private javax.swing.JLabel txtFechaInicio;
    private javax.swing.JLabel txtInforEmpresa;
    private javax.swing.JLabel txtInforFecha;
    private javax.swing.JLabel txtInforme;
    private javax.swing.JLabel txtInformeCodEmp;
    // End of variables declaration//GEN-END:variables
}
