/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Marcos
 */
public class ListaErrores extends javax.swing.JFrame {

    /**
     * Creates new form ListaErrores
     */
    public ListaErrores() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        panelFondoLista = new javax.swing.JPanel();
        panelListaSuperior = new javax.swing.JPanel();
        listaFecha = new javax.swing.JLabel();
        nomListaEmpresa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        botonListaSalir = new javax.swing.JButton();
        inputFechaInicialErrores = new com.toedter.calendar.JDateChooser();
        inputFechaFinalErrores = new com.toedter.calendar.JDateChooser();
        txtFechaInicialErrores = new javax.swing.JLabel();
        botonGenerarListaErrores = new javax.swing.JButton();
        txtFechaFinalErrores = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jMenu1.add(jRadioButtonMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(651, 392));

        panelListaSuperior.setBackground(new java.awt.Color(0, 102, 204));

        listaFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listaFecha.setForeground(new java.awt.Color(240, 240, 240));
        listaFecha.setText("Fecha");

        nomListaEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nomListaEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        nomListaEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        nomListaEmpresa.setText("CoX Manager");

        javax.swing.GroupLayout panelListaSuperiorLayout = new javax.swing.GroupLayout(panelListaSuperior);
        panelListaSuperior.setLayout(panelListaSuperiorLayout);
        panelListaSuperiorLayout.setHorizontalGroup(
            panelListaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomListaEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaFecha)
                .addGap(50, 50, 50))
        );
        panelListaSuperiorLayout.setVerticalGroup(
            panelListaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaSuperiorLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelListaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomListaEmpresa)
                    .addComponent(listaFecha)))
        );

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COD_ERROR", "CANTIDAD AFECTADA", "DESCRIPCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaErrores);

        botonListaSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonListaSalir.setText("SALIR");

        txtFechaInicialErrores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaInicialErrores.setText("Fecha Inicial:");

        botonGenerarListaErrores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonGenerarListaErrores.setText("CARGAR DATOS");

        txtFechaFinalErrores.setText("jLabel2");

        javax.swing.GroupLayout panelFondoListaLayout = new javax.swing.GroupLayout(panelFondoLista);
        panelFondoLista.setLayout(panelFondoListaLayout);
        panelFondoListaLayout.setHorizontalGroup(
            panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListaSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoListaLayout.createSequentialGroup()
                .addGroup(panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelFondoListaLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(txtFechaInicialErrores)
                            .addGap(18, 18, 18)
                            .addComponent(inputFechaInicialErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(txtFechaFinalErrores)
                            .addGap(57, 57, 57)
                            .addComponent(inputFechaFinalErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46))
                        .addGroup(panelFondoListaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(botonGenerarListaErrores)
                            .addGap(176, 176, 176)
                            .addComponent(botonListaSalir)))
                    .addGroup(panelFondoListaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelFondoListaLayout.setVerticalGroup(
            panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoListaLayout.createSequentialGroup()
                .addComponent(panelListaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFechaInicialErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFechaFinalErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicialErrores)
                    .addComponent(txtFechaFinalErrores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelFondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonListaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarListaErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarListaErrores;
    private javax.swing.JButton botonListaSalir;
    private com.toedter.calendar.JDateChooser inputFechaFinalErrores;
    private com.toedter.calendar.JDateChooser inputFechaInicialErrores;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaFecha;
    private javax.swing.JLabel nomListaEmpresa;
    private javax.swing.JPanel panelFondoLista;
    private javax.swing.JPanel panelListaSuperior;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JLabel txtFechaFinalErrores;
    private javax.swing.JLabel txtFechaInicialErrores;
    // End of variables declaration//GEN-END:variables
}
