/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Lote;
import modelo.Maquina;

/**
 *
 * @author Marcos
 */
public class Operario extends javax.swing.JFrame {

    Empleado empleado;
    Lote lote;
    Maquina maquina;
    int emple2;
    int emple3;
    String horaInicial;
    String codError;
    RegistroErrores re;
    
    public Operario(Empleado emp, Lote lote, Maquina maq, int emp2, int emp3, String horaIni){
        initComponents();
        this.setVisible(true);
        
        this.empleado = emp;
        this.lote = lote;
        this.maquina = maq;
        this.emple2 = emp2;
        this.emple3 = emp3;
        this.horaInicial = horaIni;
        
        txtOperEmple.setText("EMPLEADO: " + empleado.getCodEmpleado());
        txtOperLote.setText("LOTE: " + lote.getCodLote());
        txtOperMaquina.setText("MAQUINA: " + maquina.getCodMaquina());
        txtOperFecha.setText(GestorBD.fecha());
        this.setTitle(String.valueOf(empleado.getCodEmpleado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelOperSuperior1 = new javax.swing.JPanel();
        txtOperFecha = new javax.swing.JLabel();
        txtOperEmpresa = new javax.swing.JLabel();
        txtOperEmple = new javax.swing.JLabel();
        txtOperLote = new javax.swing.JLabel();
        txtOperMaquina = new javax.swing.JLabel();
        botonOperRegError = new javax.swing.JButton();
        botonOperSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(631, 380));
        setResizable(false);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOperSuperior1.setBackground(new java.awt.Color(0, 102, 204));
        panelOperSuperior1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtOperFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtOperFecha.setText("Fecha");
        panelOperSuperior1.add(txtOperFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        txtOperEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtOperEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtOperEmpresa.setText("CoX Manager");
        panelOperSuperior1.add(txtOperEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        panelFondo.add(panelOperSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        txtOperEmple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOperEmple.setText("EMPLEADO: COD_EMP");
        panelFondo.add(txtOperEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, -1));

        txtOperLote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOperLote.setText("MAQUINA: COD_MAQUINA");
        panelFondo.add(txtOperLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        txtOperMaquina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOperMaquina.setText("LOTE: COD_LOTE");
        panelFondo.add(txtOperMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        botonOperRegError.setText("REGISTRAR ERROR");
        botonOperRegError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperRegErrorActionPerformed(evt);
            }
        });
        panelFondo.add(botonOperRegError, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 140, 60));

        botonOperSalir.setText("SALIR");
        botonOperSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperSalirActionPerformed(evt);
            }
        });
        panelFondo.add(botonOperSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOperRegErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperRegErrorActionPerformed
        if(re == null){
            re = new RegistroErrores(this);
        this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Ya se ha registrado un error.\nCodigo:"+re.getCodErrorRegistrado());
        }
    }//GEN-LAST:event_botonOperRegErrorActionPerformed

    private void botonOperSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperSalirActionPerformed
        String fichados = "";
        try {
            if(re == null){
                GestorBD.registrarFichajeSinError(this.empleado.getCodEmpleado(),this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial);
                fichados += this.empleado.getCodEmpleado();
                if(this.emple2 != 0){
                    GestorBD.registrarFichajeSinError(this.emple2,this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial);
                    fichados += ", " + this.emple2;
                    if(this.emple3 != 0){
                        GestorBD.registrarFichajeSinError(this.emple3,this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial);
                        fichados += ", " + this.emple3;
                    }
                }
                
            }
            else{
                GestorBD.registrarFichajeConError(this.empleado.getCodEmpleado(),this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial,re.getCodErrorRegistrado());
                fichados += this.empleado.getCodEmpleado();
                if(this.emple2 != 0){
                    GestorBD.registrarFichajeConError(this.emple2,this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial,re.getCodErrorRegistrado());
                    fichados += ", " + this.emple2;
                    if(this.emple3 != 0){
                        GestorBD.registrarFichajeConError(this.emple3,this.lote.getCodLote(),this.maquina.getCodMaquina(),
                                        this.horaInicial,re.getCodErrorRegistrado());
                        fichados += ", " + this.emple3;
                    }
                }
                fichados += "\nCon error: " + re.getCodErrorRegistrado();
            }
            if (maquina.getCodMaquina() == 7){
                fichados += "\n Lote " + lote.getCodLote() + " terminado. Registrado como \"NO ACTIVO\" en Base de Datos.";
            }
            JOptionPane.showMessageDialog(this, "Registrado el fichaje para: " + fichados);
            Fichaje f = new Fichaje();
            this.setVisible(false);
        } 
        catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonOperSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOperRegError;
    private javax.swing.JButton botonOperSalir;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelOperSuperior1;
    private javax.swing.JLabel txtOperEmple;
    private javax.swing.JLabel txtOperEmpresa;
    private javax.swing.JLabel txtOperFecha;
    private javax.swing.JLabel txtOperLote;
    private javax.swing.JLabel txtOperMaquina;
    // End of variables declaration//GEN-END:variables

    public String getCodEmpOper(){
        return String.valueOf(this.empleado.getCodEmpleado());
    }
    
    public String getCodLoteOper(){
        return String.valueOf(this.lote.getCodLote());
    }

    public String getNomMaqOper(){
        return String.valueOf(this.maquina.getNombreMaquina());
    }
    
    public void setCodError(String codErr){
        this.codError = codErr;
    }
    
    public void volver(){
        this.setVisible(true);
    }
}
