/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class RegistroLote extends javax.swing.JFrame {

    VistaEncargado e;
    public RegistroLote(VistaEncargado encarg) {
        initComponents();
        this.setVisible(true);
        fechaRegLote.setText(GestorBD.fecha());
        this.e = encarg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperiorRegLote = new javax.swing.JPanel();
        fechaRegLote = new javax.swing.JLabel();
        regLoteTxtEmpresa = new javax.swing.JLabel();
        inputCodLote = new javax.swing.JTextField();
        txtCodLote = new javax.swing.JLabel();
        txtTipoLote = new javax.swing.JLabel();
        btnRegistrarLote = new javax.swing.JButton();
        btnCancelarRegLote = new javax.swing.JButton();
        inputTipoLote = new javax.swing.JTextField();
        checkImperf = new javax.swing.JCheckBox();
        txtCantidadLote = new javax.swing.JLabel();
        inputCantLote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperiorRegLote.setBackground(new java.awt.Color(0, 102, 204));

        fechaRegLote.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fechaRegLote.setForeground(new java.awt.Color(240, 240, 240));
        fechaRegLote.setText("Fecha");

        regLoteTxtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        regLoteTxtEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        regLoteTxtEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        regLoteTxtEmpresa.setText("CoX Manager");

        javax.swing.GroupLayout panelSuperiorRegLoteLayout = new javax.swing.GroupLayout(panelSuperiorRegLote);
        panelSuperiorRegLote.setLayout(panelSuperiorRegLoteLayout);
        panelSuperiorRegLoteLayout.setHorizontalGroup(
            panelSuperiorRegLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorRegLoteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regLoteTxtEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(fechaRegLote)
                .addGap(73, 73, 73))
        );
        panelSuperiorRegLoteLayout.setVerticalGroup(
            panelSuperiorRegLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorRegLoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuperiorRegLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLoteTxtEmpresa)
                    .addComponent(fechaRegLote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelSuperiorRegLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));
        jPanel1.add(inputCodLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 160, -1));

        txtCodLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodLote.setText("Código de lote:");
        jPanel1.add(txtCodLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtTipoLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipoLote.setText("Número de tipo:");
        jPanel1.add(txtTipoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        btnRegistrarLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarLote.setText("REGISTRAR");
        btnRegistrarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLoteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 40));

        btnCancelarRegLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarRegLote.setText("CANCELAR");
        jPanel1.add(btnCancelarRegLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        inputTipoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoLoteActionPerformed(evt);
            }
        });
        jPanel1.add(inputTipoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 160, -1));

        checkImperf.setText("Imperfección");
        jPanel1.add(checkImperf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        txtCantidadLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidadLote.setText("Cantidad:");
        jPanel1.add(txtCantidadLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel1.add(inputCantLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTipoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoLoteActionPerformed

    private void btnRegistrarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLoteActionPerformed
        int codigo = 0;
        try{
            codigo = Integer.parseInt(inputCodLote.getText());
            int tipo = Integer.parseInt(inputTipoLote.getText());
            int cantidad = Integer.parseInt(inputCantLote.getText());
            GestorBD.altaLote(codigo, tipo, cantidad, checkImperf.isSelected());
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Todos los campos del registro son numéricos.");
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        JOptionPane.showMessageDialog(this, "Lote " + codigo + "registrado por el empleado " + e.getCodEmpEncar());
        this.setVisible(false);
        e.volver();
    }//GEN-LAST:event_btnRegistrarLoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegLote;
    private javax.swing.JButton btnRegistrarLote;
    private javax.swing.JCheckBox checkImperf;
    private javax.swing.JLabel fechaRegLote;
    private javax.swing.JTextField inputCantLote;
    private javax.swing.JTextField inputCodLote;
    private javax.swing.JTextField inputTipoLote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelSuperiorRegLote;
    private javax.swing.JLabel regLoteTxtEmpresa;
    private javax.swing.JLabel txtCantidadLote;
    private javax.swing.JLabel txtCodLote;
    private javax.swing.JLabel txtTipoLote;
    // End of variables declaration//GEN-END:variables
}
