/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class RegistroEmpleado extends javax.swing.JFrame {

    int tipoEmpleado;
    VistaGestor vG;
    
    public RegistroEmpleado(VistaGestor vistaG) {
        initComponents();
        this.setVisible(true);
        this.vG = vistaG;
        txtRegEmpFecha.setText(GestorBD.fecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoRegEmpleado = new javax.swing.JPanel();
        panelRegErrSuperior = new javax.swing.JPanel();
        txtRegEmpFecha = new javax.swing.JLabel();
        txtRegEmpEmpresa = new javax.swing.JLabel();
        btnRegEmple = new javax.swing.JButton();
        btnSalirRegEmple = new javax.swing.JButton();
        txtRegDniEmple = new javax.swing.JLabel();
        txtNombreRegEmple = new javax.swing.JLabel();
        txtTelefRegEmple = new javax.swing.JLabel();
        inputRegEmpleDNI = new javax.swing.JTextField();
        inputRegEmpleNombre = new javax.swing.JTextField();
        inputRegEmpleTlf = new javax.swing.JTextField();
        txtNotaRegEmple = new javax.swing.JLabel();
        selectorTipoEmpleado = new javax.swing.JComboBox<>();
        txtTipoRegEmple = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 400));
        setResizable(false);

        panelFondoRegEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegErrSuperior.setBackground(new java.awt.Color(0, 102, 204));
        panelRegErrSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegEmpFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRegEmpFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtRegEmpFecha.setText("Fecha");
        panelRegErrSuperior.add(txtRegEmpFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        txtRegEmpEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtRegEmpEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtRegEmpEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        txtRegEmpEmpresa.setText("CoX Manager");
        panelRegErrSuperior.add(txtRegEmpEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelFondoRegEmpleado.add(panelRegErrSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        btnRegEmple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegEmple.setText("REGISTRAR");
        btnRegEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegEmpleActionPerformed(evt);
            }
        });
        panelFondoRegEmpleado.add(btnRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 140, 50));

        btnSalirRegEmple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirRegEmple.setText("CANCELAR");
        btnSalirRegEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegEmpleActionPerformed(evt);
            }
        });
        panelFondoRegEmpleado.add(btnSalirRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 110, 40));

        txtRegDniEmple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRegDniEmple.setText("DNI:");
        panelFondoRegEmpleado.add(txtRegDniEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtNombreRegEmple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreRegEmple.setText("Nombre y apellidos:");
        panelFondoRegEmpleado.add(txtNombreRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtTelefRegEmple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefRegEmple.setText("Nº de teléfono:");
        panelFondoRegEmpleado.add(txtTelefRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));
        panelFondoRegEmpleado.add(inputRegEmpleDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, -1));
        panelFondoRegEmpleado.add(inputRegEmpleNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, -1));
        panelFondoRegEmpleado.add(inputRegEmpleTlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, -1));

        txtNotaRegEmple.setText("Nota: Si se registra un gestor se ha de introducir contraseña");
        panelFondoRegEmpleado.add(txtNotaRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        selectorTipoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectorTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERARIO", "ENCARGADO", "GESTOR" }));
        panelFondoRegEmpleado.add(selectorTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        txtTipoRegEmple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTipoRegEmple.setText("Tipo de empleado:");
        panelFondoRegEmpleado.add(txtTipoRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoRegEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoRegEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirRegEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegEmpleActionPerformed
        this.vG.volver();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirRegEmpleActionPerformed

    private void btnRegEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegEmpleActionPerformed
        try {
            compruebaDatos();
            this.tipoEmpleado = selectorTipoEmpleado.getSelectedIndex() + 1;
            if (tipoEmpleado != 3) {
                
                int codNuevoEmp = GestorBD.altaEmpleado(tipoEmpleado, inputRegEmpleDNI.getText(), 
                        inputRegEmpleNombre.getText(),inputRegEmpleTlf.getText(), null);
                JOptionPane.showMessageDialog(this, "Registrado empleado con codigo " + codNuevoEmp);
            } 
            else {

            }
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnRegEmpleActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegEmple;
    private javax.swing.JButton btnSalirRegEmple;
    private javax.swing.JTextField inputRegEmpleDNI;
    private javax.swing.JTextField inputRegEmpleNombre;
    private javax.swing.JTextField inputRegEmpleTlf;
    private javax.swing.JPanel panelFondoRegEmpleado;
    private javax.swing.JPanel panelRegErrSuperior;
    private javax.swing.JComboBox<String> selectorTipoEmpleado;
    private javax.swing.JLabel txtNombreRegEmple;
    private javax.swing.JLabel txtNotaRegEmple;
    private javax.swing.JLabel txtRegDniEmple;
    private javax.swing.JLabel txtRegEmpEmpresa;
    private javax.swing.JLabel txtRegEmpFecha;
    private javax.swing.JLabel txtTelefRegEmple;
    private javax.swing.JLabel txtTipoRegEmple;
    // End of variables declaration//GEN-END:variables

    private void compruebaDatos() throws MyException{
        String regExpTelefono = "^\\d{9}$";
        String regExpDNI = "^\\d{8}[A-Z]$";
        if(!inputRegEmpleDNI.getText().matches(regExpDNI)){
            throw new MyException("El DNI debe tener 8 números consecutivos y una letra mayúscula al final.");
        }
        else if(inputRegEmpleNombre.getText().equals("")){
            throw new MyException("El nombre no puede estar vacío");
        }
        else if(inputRegEmpleNombre.getText().length() > 30){
            throw new MyException("El nombre deben ser menos de 30 carácteres en total.");
        }
        else if(!inputRegEmpleTlf.getText().matches(regExpTelefono)){
            throw new MyException("El telefono deben ser 9 digitos seguidos.");
        }
    }
}
