/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Lote;
import modelo.Maquina;

/**
 *
 * @author Marcos
 */
public class RegistroErrores extends javax.swing.JFrame {
    
    Operario oper;
    Encargado encar;
    Gestor gestor;
    String nomMaquina;
    String codLote;
    String codEmple;
    String codError;
    
    public RegistroErrores(Operario o) {
        initComponents();
        this.setVisible(true);
        
        this.oper = o;
        this.nomMaquina = o.getNomMaqOper();
        this.codLote = o.getCodLoteOper();
        this.codEmple = o.getCodEmpOper();
        this.setTitle("Registro de error");
        this.txtRegErrFecha.setText(GestorBD.fecha());
    }
    
    public RegistroErrores(Encargado e) {
        initComponents();
        this.setVisible(true);
        
        this.encar = e;
        this.nomMaquina = e.getNomMaqEncar();
        this.codLote = e.getCodLoteEncar();
        this.codEmple = e.getCodEmpEncar();
        this.setTitle("Registro de error");
        this.txtRegErrFecha.setText(GestorBD.fecha());
    }
    
    public RegistroErrores(Gestor g) {
        initComponents();
        this.setVisible(true);
        
        this.gestor = g;
        this.setTitle("Registro de error");
        this.txtRegErrFecha.setText(GestorBD.fecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOperSuperior1 = new javax.swing.JPanel();
        txtOperFecha = new javax.swing.JLabel();
        txtOperEmpresa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelRegErrSuperior = new javax.swing.JPanel();
        txtRegErrFecha = new javax.swing.JLabel();
        txtRegErrEmpresa = new javax.swing.JLabel();
        inputRegErrCant = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputRegErrDesc = new javax.swing.JTextArea();
        botonRegError = new javax.swing.JButton();
        txtRegErrCant = new javax.swing.JLabel();
        txtRegErrDesc = new javax.swing.JLabel();
        botonSalirRegError = new javax.swing.JButton();

        panelOperSuperior1.setBackground(new java.awt.Color(0, 102, 204));
        panelOperSuperior1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtOperFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtOperFecha.setText("Fecha");
        panelOperSuperior1.add(txtOperFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        txtOperEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtOperEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtOperEmpresa.setText("CoX Manager");
        panelOperSuperior1.add(txtOperEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 400));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 400));

        panelRegErrSuperior.setBackground(new java.awt.Color(0, 102, 204));
        panelRegErrSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegErrFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRegErrFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtRegErrFecha.setText("Fecha");
        panelRegErrSuperior.add(txtRegErrFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        txtRegErrEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtRegErrEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtRegErrEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_CoX.png"))); // NOI18N
        txtRegErrEmpresa.setText("CoX Manager");
        panelRegErrSuperior.add(txtRegErrEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        inputRegErrCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRegErrCantActionPerformed(evt);
            }
        });

        inputRegErrDesc.setColumns(20);
        inputRegErrDesc.setRows(5);
        jScrollPane1.setViewportView(inputRegErrDesc);

        botonRegError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonRegError.setText("REGISTRAR");
        botonRegError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegErrorActionPerformed(evt);
            }
        });

        txtRegErrCant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRegErrCant.setText("Cantidad Afectada:");

        txtRegErrDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRegErrDesc.setText("Descripción:");

        botonSalirRegError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonSalirRegError.setText("CANCELAR");
        botonSalirRegError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirRegErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegErrSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegErrCant, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegErrDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalirRegError, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputRegErrCant, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(botonRegError, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelRegErrSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRegErrCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegErrCant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRegErrDesc)
                        .addGap(56, 56, 56)
                        .addComponent(botonSalirRegError, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegError, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputRegErrCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRegErrCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRegErrCantActionPerformed

    private void botonRegErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegErrorActionPerformed

        try{
            String codErr = this.nomMaquina.substring(0, 3) + this.codLote + GestorBD.numErrores();
            int cantidad = Integer.parseInt(inputRegErrCant.getText());
            this.codError = codErr;
            if(GestorBD.registrarError(codErr, inputRegErrDesc.getText(), cantidad, GestorBD.horaActual())){
                
                JOptionPane.showMessageDialog(this, "Error "+ codErr+" registrado por el empleado:" + this.codEmple);
                this.setVisible(false);
                
                switch (codEmple.charAt(0)) {
                    case '1':
                        oper.volver();
                        break;
                    case '2':
                        encar.volver();
                        break;
                    default:
                        gestor.volver();
                        break;
                }
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "No se ha insertado ninguna fila.");
            }
        }
        catch (MyException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (NumberFormatException num){
            JOptionPane.showMessageDialog(this, "La cantidad debe ser numérica.");
        }
    }//GEN-LAST:event_botonRegErrorActionPerformed

    private void botonSalirRegErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirRegErrorActionPerformed
        switch (codEmple.charAt(0)) {
            case '1':
                oper.volver();
                break;
            case '2':
                encar.volver();
                break;
            default:
                gestor.volver();
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirRegErrorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegError;
    private javax.swing.JButton botonSalirRegError;
    private javax.swing.JTextField inputRegErrCant;
    private javax.swing.JTextArea inputRegErrDesc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelOperSuperior1;
    private javax.swing.JPanel panelRegErrSuperior;
    private javax.swing.JLabel txtOperEmpresa;
    private javax.swing.JLabel txtOperFecha;
    private javax.swing.JLabel txtRegErrCant;
    private javax.swing.JLabel txtRegErrDesc;
    private javax.swing.JLabel txtRegErrEmpresa;
    private javax.swing.JLabel txtRegErrFecha;
    // End of variables declaration//GEN-END:variables

    public String getCodErrorRegistrado(){
        return this.codError;
    }
}
