/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import excepciones.MyException;
import gestor.GestorBD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author Marcos
 */
public class VistaGestor extends javax.swing.JFrame {

    Empleado empleado;
    String horaInicial;
    
    public VistaGestor(Empleado e, String horaIni) {
        initComponents();
        this.setVisible(true);
        this.empleado = e;
        this.horaInicial = horaIni;
        
        txtGestorEmple.setText("EMPLEADO: " + empleado.getCodEmpleado());
        txtGestorFecha.setText(GestorBD.fecha());
        this.setTitle(String.valueOf(empleado.getCodEmpleado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        gestorPanelSuperior1 = new javax.swing.JPanel();
        txtGestorFecha = new javax.swing.JLabel();
        txtGestorEmpresa = new javax.swing.JLabel();
        txtGestorEmple = new javax.swing.JLabel();
        botonOperRegError = new javax.swing.JButton();
        botonOperInformes = new javax.swing.JButton();
        botonOperSalir = new javax.swing.JButton();
        botonGestorListaErr = new javax.swing.JButton();
        botonOperRegEmple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(631, 352));

        panelFondo.setBackground(new java.awt.Color(204, 204, 204));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestorPanelSuperior1.setBackground(new java.awt.Color(0, 102, 204));

        txtGestorFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGestorFecha.setForeground(new java.awt.Color(240, 240, 240));
        txtGestorFecha.setText("Fecha");

        txtGestorEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtGestorEmpresa.setForeground(new java.awt.Color(240, 240, 240));
        txtGestorEmpresa.setText("CoX Manager");

        javax.swing.GroupLayout gestorPanelSuperior1Layout = new javax.swing.GroupLayout(gestorPanelSuperior1);
        gestorPanelSuperior1.setLayout(gestorPanelSuperior1Layout);
        gestorPanelSuperior1Layout.setHorizontalGroup(
            gestorPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestorPanelSuperior1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtGestorEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(txtGestorFecha)
                .addGap(52, 52, 52))
        );
        gestorPanelSuperior1Layout.setVerticalGroup(
            gestorPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestorPanelSuperior1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(gestorPanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGestorEmpresa)
                    .addComponent(txtGestorFecha))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelFondo.add(gestorPanelSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        txtGestorEmple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGestorEmple.setText("EMPLEADO: COD_EMPLE");
        panelFondo.add(txtGestorEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        botonOperRegError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonOperRegError.setText("REGISTRAR ERROR");
        panelFondo.add(botonOperRegError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 50));

        botonOperInformes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonOperInformes.setText("INFORMES");
        botonOperInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperInformesActionPerformed(evt);
            }
        });
        panelFondo.add(botonOperInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 170, 50));

        botonOperSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonOperSalir.setText("SALIR");
        botonOperSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperSalirActionPerformed(evt);
            }
        });
        panelFondo.add(botonOperSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 130, 50));

        botonGestorListaErr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonGestorListaErr.setText("LISTA DE ERRORES");
        panelFondo.add(botonGestorListaErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, 50));

        botonOperRegEmple.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonOperRegEmple.setText("REGISTRAR EMPLEADO");
        botonOperRegEmple.setToolTipText("");
        botonOperRegEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperRegEmpleActionPerformed(evt);
            }
        });
        panelFondo.add(botonOperRegEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOperInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOperInformesActionPerformed

    private void botonOperRegEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperRegEmpleActionPerformed
        RegistroEmpleado rE = new RegistroEmpleado(this);
        this.setVisible(false);
    }//GEN-LAST:event_botonOperRegEmpleActionPerformed

    private void botonOperSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperSalirActionPerformed
        try {
            GestorBD.registroFichajeGestor(this.empleado.getCodEmpleado(),this.horaInicial);
            JOptionPane.showMessageDialog(this, "Fichaje con código " + empleado.getCodEmpleado() + " registrado.");
            Fichaje f = new Fichaje();
            this.setVisible(false);
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonOperSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestorListaErr;
    private javax.swing.JButton botonOperInformes;
    private javax.swing.JButton botonOperRegEmple;
    private javax.swing.JButton botonOperRegError;
    private javax.swing.JButton botonOperSalir;
    private javax.swing.JPanel gestorPanelSuperior1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel txtGestorEmple;
    private javax.swing.JLabel txtGestorEmpresa;
    private javax.swing.JLabel txtGestorFecha;
    // End of variables declaration//GEN-END:variables

    public String getCodEmpGestor(){
        return String.valueOf(this.empleado.getCodEmpleado());
    }
    
    public void volver(){
        this.setVisible(true);
    }

}
